// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectTasks.Api.Models;

#nullable disable

namespace ProjectTasks.Api.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240624224230_Unsyncronized")]
    partial class Unsyncronized
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectTasks.Api.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("ProjectTasks.Api.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectReferenceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectReferenceId");

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("ProjectTasks.Api.Models.UnsyncronizedProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("unsyncronized_projects");
                });

            modelBuilder.Entity("ProjectTasks.Api.Models.UnsyncronizedTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectReferenceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectReferenceId");

                    b.ToTable("unsyncronized_tasks");
                });

            modelBuilder.Entity("ProjectTasks.Api.Models.Task", b =>
                {
                    b.HasOne("ProjectTasks.Api.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectTasks.Api.Models.UnsyncronizedTask", b =>
                {
                    b.HasOne("ProjectTasks.Api.Models.UnsyncronizedProject", "UnsyncronizedProject")
                        .WithMany("UnsyncronizedTasks")
                        .HasForeignKey("ProjectReferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnsyncronizedProject");
                });

            modelBuilder.Entity("ProjectTasks.Api.Models.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ProjectTasks.Api.Models.UnsyncronizedProject", b =>
                {
                    b.Navigation("UnsyncronizedTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
