services:
  project_tasks_api:
    container_name: project_tasks_api
    build:
      context: .
      dockerfile: ProjectTasks.Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
    expose:
      - 8080
    ports:
      - 80:8080
    tty: true
