name: CI
on:
  pull_request:
    branches:
      - 'master'
jobs:
  Test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet test ProjectTasks.Tables.Tests.Unit
      - run: dotnet test ProjectTasks.Documents.Tests.Unit
